### ISSUE TITLE
Feature request - sending location via bot 

### ISSUE THREAD

**Issue by dawie180** [eugenio412/PogomBOT#1]
You guys have done an awsome job with this... to make thing more epic if we could send our location to the  bot which then changes the location of the pogom scanner.

**Comment by eugenio412** [comment]
By now the bot only reads the database, and there is no communication back. But i hope we can in the future

**Comment by kelt8** [comment]
by any chance you can implement an additional line above the map sending so that in telegram notifications i can see the title of the spawn id. and then i can see whether is it worth it to click in and check?

**Comment by eugenio412** [comment]
That's for another issue @kelt8 , see at #12
