### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by Unknown66** [eugenio412/PogomBOT#11]
I think there's a memory leak with the sent variable. (forget to fix in #10)
If I've got time I will fix it and change sent to a user based variable.

Note: Threadsafe with Locks

**Comment by eugenio412** [comment]
I guess so, I thought that but I let it go several times for time reasons

**Comment by Unknown66** [comment]
Okay I will do this and some code optimization tonight.

**Comment by eugenio412** [comment]
@Unknown66 invited you as a collaborator, I guess otherwise i can't assign you anything
