### ISSUE TITLE
Token Invalid Syntax

### ISSUE THREAD

**Issue by MrRogerino** [eugenio412/PogomBOT#13]
When I paste the token from @BotFather, I see this: http://puu.sh/qGKRh/1ea19d33c8.png.

Any idea what the issue is? I've tried deleting the colon indicated. but it still states that there's invalid syntax.

**Comment by eugenio412** [comment]
Yes, you just forgot to put "", like "TOKEN", not TOKEN alone

**Comment by MrRogerino** [comment]
Ah, my bad! Sorry for the inconvenience.
