### ISSUE TITLE
Request: make rarity categories configurable

### ISSUE THREAD

**Issue by Korzakov** [eugenio412/PogomBOT#19]
The rarity categories which are currently used in the bot are not really suited for the area I live in. I'd like to change the categories. Would it maybe possible to move rarity categories out of the pogobot.py to config.json?

**Comment by eugenio412** [comment]
That's a good idea, by the way with the function /save the bot gives you directly the numbers of the pokemon scanned, so it's easier to get it back inside. I guess this would be not necessary as soon as we implement a persistence for the scanner.

**Comment by dikkedeur** [comment]
i just made a new row with the ids that i want to be notified about.
then i use on the bot..
/addbyrarity 6 ( since its after the 5 other ones ^^ )
problem is when you update the application, you need to insert them again, so i have a copy of the line.

**Comment by Korzakov** [comment]
@eugenio412 and @Unknown66 this issue has been closed, but the categories are still in pogobot.py. Everytime I do a git pull my categories are overwritten. Or am I missing something? 
P.S. Great work on the bot!

**Comment by eugenio412** [comment]
Yes, that's true, but it doesn't make a lot of sense to change the categories once that you saved your favourite Pokemon using /save and /load, you can have it right back using this commands
