### ISSUE TITLE
[error] cannot import timezone

### ISSUE THREAD

**Issue by dikkedeur** [eugenio412/PogomBOT#24]
Updated to latest version.
upon starting the bot i get

Traceback (most recent call last):
  File "pogobot.py", line 18, in <module>
    from datetime import datetime, timezone
ImportError: cannot import name timezone

**Comment by Unknown66** [comment]
Did you run with python3?

**Comment by dikkedeur** [comment]
when i do that i get this

root@logon:~/pogom# python3 pogobot.py 
Traceback (most recent call last):
  File "pogobot.py", line 14, in <module>
    from telegram.ext import Updater, CommandHandler, Job
ImportError: No module named 'telegram'

**Comment by dikkedeur** [comment]
python --version
Python 2.7.12

never had problem, been using it since 2 days

**Comment by Unknown66** [comment]
Timezone is from python3.
You installed dependencies for python2.

Steps to fix:
1. `sudo pip3 install -r requirements.txt -U`
2. `python3 pogobot.py`

now it should work!

Since this #21.

**Comment by dikkedeur** [comment]
no i didnt, i thought it was only needed the first time you clone the repo..
will do and report back.

**Comment by Unknown66** [comment]
Normally you only need it first time clone. Thats mysterious!

**Comment by dikkedeur** [comment]
works now with python3 pogobot.py
thanks..

**Comment by Unknown66** [comment]
#25 will now raise an exception for this bug thanks and no problem :+1:
