### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by Unknown66** [eugenio412/PogomBOT#26]
Should we do a troubleshooting guide on the wiki page? @eugenio412

**Comment by eugenio412** [comment]
I think it's a good idea! Starting with the posted issues, I can do it. I was also thinking that we can open a group on telegram for faster interaction, like the one on Python-telegram-bot

**Comment by Unknown66** [comment]
Good idea! https://gitter.im/ would be nice too because its mainly used for github.
