### ISSUE TITLE
Multiple notifications for same pokemon

### ISSUE THREAD

**Issue by Korzakov** [eugenio412/PogomBOT#27]
I just updated to the latest version. Nice work on that.

But now i get multiple notifications for the same pokemon. I think its because pogom add multiple entries for the same pokemon in the database. The encounter_id is the same, but disappear_time is different.

**Comment by Korzakov** [comment]
Here are some screenshots of the stats and the database.
![database](https://cloud.githubusercontent.com/assets/21110690/17832895/20a21a7e-670f-11e6-9c0b-ab22525471a5.PNG)
![stats](https://cloud.githubusercontent.com/assets/21110690/17832894/20a2110a-670f-11e6-8f76-04708983b246.PNG)

I got a notification for each row in the database :stuck_out_tongue_closed_eyes:

Btw, I also created an issue on the pogom repo about these multiple rows.

**Comment by eugenio412** [comment]
As you said it is a pogom bug, we can do something to correct that but they should fix it either. I guess I should add a second check to ensure that the notification is not duplicated

**Comment by Unknown66** [comment]
Mhh interesting I haven't had that problem by now.

**Comment by Korzakov** [comment]
Probably a pogom bug indeed. Had to start over with a new db according to nbormann from pogom. Will try tomorrow. Don't put any effort into this now :)

**Comment by Korzakov** [comment]
A newly created database fixed the issue. Primary key issue, now the PK is only on encounter_id. First it was on encounter_id and disappear_time.  

You can close this issue!
