### ISSUE TITLE
No module named 'telegram'

### ISSUE THREAD

**Issue by RubenHiem** [eugenio412/PogomBOT#31]
Traceback (most recent call last):
  File "pogobot.py", line 19, in <module>
    from telegram.ext import Updater, CommandHandler, Job
ImportError: No module named 'telegram'
...

What is the problem?

**Comment by eugenio412** [comment]
Did you run the requirements? Be careful, use pip3

**Comment by RubenHiem** [comment]
Thanks, i think thats the issue!

**Comment by RubenHiem** [comment]
The only problem is that pip3 doesn't work on my server.

**Comment by Unknown66** [comment]
`sudo apt-get install python3 python3-pip` should get you pip3 and python3.

**Comment by RubenHiem** [comment]
No package available python3 and python3-pip

**Comment by eugenio412** [comment]
@RubenHiem which OS are you using? Ubuntu, debian?

**Comment by RubenHiem** [comment]
@eugenio412 Centos 7

**Comment by Unknown66** [comment]
@RubenHiem [This](http://ask.xmodulo.com/install-python3-centos.html) and [this](http://stackoverflow.com/questions/32618686/how-to-install-pip-in-centos-7) should help to install python3 with pip3.

**Comment by RubenHiem** [comment]
@Unknown66: Already tried:

[root@server1 PogomBOT]# python3.5 get-pip.py
Requirement already up-to-date: pip in /usr/local/lib/python3.5/site-packages
[root@server1 PogomBOT]# pip3

Usage:
  pip <command> [options]

**Comment by RubenHiem** [comment]
But if I run the requirements, this is the output:

Requirement already up-to-date: python-telegram-bot==5.0.0 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already up-to-date: future>=0.15.2 in /usr/lib/python2.7/site-packages (from python-telegram-bot==5.0.0->-r requirements.txt (line 1))
Requirement already up-to-date: urllib3>=1.10 in /usr/lib/python2.7/site-packages (from python-telegram-bot==5.0.0->-r requirements.txt (line 1))
Requirement already up-to-date: certifi in /usr/lib/python2.7/site-packages (from python-telegram-bot==5.0.0->-r requirements.txt (line 1))

So he is using te wrong pip i guess

**Comment by eugenio412** [comment]
Yes, you need pip3

**Comment by RubenHiem** [comment]
Yeah I know, its installed but not working

**Comment by PhDeez** [comment]
What's the output of:

`pip3 --version`

because based on the output above, you installed the requirements via pip (which defaults to python 2.7) instead of pip3.

What's the output of this command?

`sudo pip3 install -r requirements.txt -U`

**Comment by RubenHiem** [comment]
Thanks for helping, this is the output:

[root@server1 ~]# pip3 --version
pip 8.1.2 from /usr/local/lib/python3.5/site-packages (python 3.5)
[root@server1 ~]# cd PogomBOT/
[root@server1 PogomBOT]# sudo pip3 install -r requirements.txt -U
sudo: pip3: command not found
[root@server1 PogomBOT]#

**Comment by PhDeez** [comment]
It's super odd that you can run pip3 from the command line but the system doesn't see it there when running it via sudo.  If you're logged in as root, I'd skip the sudo portion and see if that works.  

If that doesn't work, maybe you can run it via /usr/bin/pip3 like this:
#cd ~/PogomBot/
#/usr/bin/pip3 install -r requirements.txt -U
