### ISSUE TITLE
Set bot in a channel

### ISSUE THREAD

**Issue by Made123** [eugenio412/PogomBOT#34]
## Checklist

I succeed install and using the pogomBOT, very nice work guyz
## My Request

I will be glad to you, developping this following one.

The bot is amazing, i scan my city and want to share my information with my friends by telegram notification.
Talk to the bot is not very good because my friends can set my bot parameters and that is not very cool.

I would like to have the possibility to parameter the bot only by me and have a privacy channel where only the bot can publish the notification message. And the people who join the channel will can only read the message and write nothing.
It will be amazing !

Thx all devs.

**Comment by Unknown66** [comment]
The other **can't** change your parameters. These are saved per user. (added in #10 and #21)
That means everyone can have a private chat with the bot.

**Comment by eugenio412** [comment]
that's basically the channel request by #6

**Comment by Unknown66** [comment]
You think we only need one channel? Then we should add this to `config-bot.json`.
This way no one else will be allowed to edit anything.

**Comment by eugenio412** [comment]
yes, but it's not that user friendly to find the chat_id of a channel

**Comment by mecorx** [comment]
I tried having 2 private chats with the bot, but it sent each person one half of the notifications.
On another note, PokeAlarm seems to work with channels: https://github.com/kvangent/PokeAlarm/wiki/Telegram

**Comment by eugenio412** [comment]
What do you mean one half? It should send the notification that every group/user set, didn't it work? And by the way, how can you have two private chats? Please explain properly the bug so I can reproduce it. 

Please @mecorx describe how to reproduce it in a brand new issue

**Comment by mecorx** [comment]
For example, I had both users set /setbyrarity 5 in separate private
conversations with the bot but one user got a notification for Dragonite
but the other did not. Basically, if one user got a notification, the other
would not get the same notification. I tried this a week+ ago, though. Not
sure if this still occurs.

**Comment by Unknown66** [comment]
It doesn't still occur anymore.
