### ISSUE TITLE
Feature Request/How To Request - Ability to monitor log of pogom and send message on error 3 (suspended account)

### ISSUE THREAD

**Issue by PhDeez** [eugenio412/PogomBOT#35]
## Checklist
- [X] I've read the [WIKI](https://github.com/eugenio412/pogomBOT/wiki)
- [X] I have checked if this issue already exists (both open and closed issues)
- [X] I am using the most recent version of pogomBOT from the master branch
- [-] If this is an installation issue, I am posting my OS, OS version, python version, pip version
- [-] I'm posting the complete log, best if using pastebin for long outputs
- [X] I'm using a descriptive title for this issue

I'm really loving the telegram Bot.  What I would like to do is send an update via telegram via my Bot telling me if I have account that has been suspended.  As it is right now the only way I can check this is to view the log file on the server.  Although I think the creators at pogom should offer some sort of message under the server config page, I've pretty much moved away from using the pogom map interface entirely, unless there are problems.

Since this application is specific to pogom, I think offering this would be very cool.  If it's too much of an ask, I can try and track down a log monitor that sends messages to Telegram, but honestly I think everyone could benefit from this.

**Comment by eugenio412** [comment]
For sure would be nice, but we don't have enough "coding power" to do it, as for now we are basically in two, and what you are asking would need a fork of pogom with a lot of mods. I'm personally under a tight deadline for what concern my studies. I guess that the inline update I'm working with it's the best we can do ritgh now. It would need more people to do all the amazing ideas that everyone is writing here. But everyone is welcome collaborating, merging and issuing here.
