### ISSUE TITLE
Error - `token` or `bot` must be passed

### ISSUE THREAD

**Issue by hamuster** [eugenio412/PogomBOT#36]
## Checklist
- [x] I've read the [WIKI](https://github.com/eugenio412/pogomBOT/wiki)
- [x] I have checked if this issue already exists (both open and closed issues)
- [x] I am using the most recent version of pogomBOT from the master branch
- [x] If this is an installation issue, I am posting my OS, OS version, python version, pip version
- [ ] I'm using a descriptive title for this issue
  - [x] I'm posting the complete log, best if using pastebin for long outputs
## My Issue

  After I reinstall my github and python. Couldn't get it to work. Dont know where went wrong, pls help.

Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.

> > > ================================ RESTART ================================
> > > 
> > > 2016-08-25 17:30:15,329 - **main**:430 - INFO - Starting...
> > > 2016-08-25 17:30:15,382 - **main**:354 - INFO - Reading config.
> > > 2016-08-25 17:30:15,382 - **main**:363 - ERROR - ValueError('Invalid control character at: line 2 column 21 (char 22)',)
> > > 2016-08-25 17:30:15,382 - **main**:367 - INFO - Reading pokemon names. [de]
> > > 2016-08-25 17:30:15,382 - **main**:367 - INFO - Reading pokemon names. [en]
> > > 2016-08-25 17:30:15,398 - **main**:367 - INFO - Reading pokemon names. [fr]
> > > 2016-08-25 17:30:15,398 - **main**:367 - INFO - Reading pokemon names. [zh_cn]
> > > 2016-08-25 17:30:15,398 - **main**:439 - INFO - Token: None
> > > Traceback (most recent call last):
> > >   File "C:\Users\hamu7\Documents\GitHub\pogom\pogobot.py", line 472, in <module>
> > >     main()
> > >   File "C:\Users\hamu7\Documents\GitHub\pogom\pogobot.py", line 440, in main
> > >     updater = Updater(token)
> > >   File "C:\Python34\lib\site-packages\telegram\ext\updater.py", line 70, in **init**
> > >     raise ValueError('`token` or `bot` must be passed')
> > > ValueError: `token` or `bot` must be passed

**Comment by Unknown66** [comment]
Seems like your configfile isn't valid. Please check the syntax.
Don't forget the trailing `"`

**Comment by hamuster** [comment]
Thank you, there was a enter between the " and the token but its was not visible, someting weird.
Now its working.

**Comment by Unknown66** [comment]
Fine :+1:
