### ISSUE TITLE
More exaustive readme

### ISSUE THREAD

**Issue by gschmall** [eugenio412/PogomBOT#4]
Not everyone is familiar with setting up a telegram bot. Please add a link to this page

https://core.telegram.org/bots

on your readme to help others get up to speed. Thanks.

**Comment by eugenio412** [comment]
I'll do it tomorrow, or if you want you can pull a request, I'll be happy to merge it

**Comment by eugenio412** [comment]
Is it fine now? should I add something more? Take a look to the readme now

**Comment by gschmall** [comment]
Id also like to suggest the following clarifications:Create a new bot and COPY THE TOKEN INSIDE the file pogobot.py in the place of TOKENtoCreate a new bot and copy the token given. Then edit pogobot.py and replace TOKEN with the one from your bot.looking good otherwise.thanks.-gschmall.On August 18, 2016 at 5:32 AM eugenio412 notifications@github.com wrote:Is it fine now? should I add something more? Take a look to the readme now—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by eugenio412** [comment]
@gschmall moved the clarification to our wiki
