### ISSUE TITLE
Add class for userdependant data.

### ISSUE THREAD

**Issue by Unknown66** [eugenio412/PogomBOT#56]
Like title:
- Add new userdependant data easier
- Dont worry about it's getting saved

**Comment by wardsimon** [comment]
I'll have a look and write some test code..

**Comment by Unknown66** [comment]
@simonward86 were you successful?

**Comment by wardsimon** [comment]
Hey,
I've had a bit of work this week, so things have been slow. I'm working on something and have a bit of time this weekend, so I'll use it to try and get it up and running.

**Comment by Unknown66** [comment]
Okay cool! Take the time you need it's only a hobby project :D

**Comment by wardsimon** [comment]
I've finished with the preferences and it works for my testing. See commit a187598951c5e54816ccd4db09d389f2dca55415
Also I've moved to the geopy package as it is much easier :-)

I'd suggest creating a new branch and beginning the testing process.

**Comment by Unknown66** [comment]
Added with #63 by @simonward86.
