### ISSUE TITLE
[Feature Request] - Whitelist for users

### ISSUE THREAD

**Issue by ematiasnt** [eugenio412/PogomBOT#64]
code from - https://github.com/muse/Lytebot

def whitelist(self, sub):
        '''
        Whitelist a sub from the /r command

```
    :param sub: Subreddit to whitelist
    '''
    try:
        self.blacklisted.remove(sub.lower())
    except ValueError:
        return

    self.save_data(self.paths['blacklisted'], self.blacklisted)
```

@lytebot.command('whitelist', admin=True)
def whitelist(args, user):
    subs = []

```
for s in args.text.split(' ')[1::]:
    lytebot.whitelist(s)
    subs.append(s)

if subs:
    logging.info('Sub(s) \'{}\' whitelisted by {}'.format(', '.join(subs), user))
    return '@{} Whitelisted {}'.format(user, ', '.join(subs))
```

**Comment by Unknown66** [comment]
I don't get it sry.

Could you please explain the intention.
And one example usage.

**Comment by ematiasnt** [comment]
I want to restrict Who send commands to the bot, and Who Will see what the bot do

**Comment by Unknown66** [comment]
For all users or only groups?

**Comment by ematiasnt** [comment]
All users

**Comment by Unknown66** [comment]
Okay. Should all users that are whitelisted be able to alter the whitelist?

**Comment by PhDeez** [comment]
Can you limit who views your bot?  I could see the whitelist for "who can send commands" but just seeing the bot's notifications?

**Comment by Unknown66** [comment]
If someone is not allowed to send commands he won't get any notifications because he's not able to alter the notifications list.
(this feature is not available by now)

**Comment by ematiasnt** [comment]
> Okay. Should all users that are whitelisted be able to alter the whitelist?

 No, Only one person. Administrator...

**Comment by Unknown66** [comment]
Okay current plan:

setting inside config-bot.json ADMIN_LIST with all admins that are able to alter the whitelist.
/wladd /wlrem to alter the whitelist.

**Comment by Unknown66** [comment]
Added with commit d0b844693c538b8498593b2946e079cbab86dc3f.

**Comment by Unknown66** [comment]
`userName` from users is used.
Would be possible to use `chatId` instead.

Waiting for feedback now!
