### ISSUE TITLE
GeocoderServiceError on Linux

### ISSUE THREAD

**Issue by pki0** [eugenio412/PogomBOT#68]
## Checklist
- [x] I've read the [WIKI](https://github.com/eugenio412/pogomBOT/wiki)
- [x] I have checked if this issue already exists (both open and closed issues)
- [x] I am using the most recent version of pogomBOT from the master branch
- [x] If this is an installation issue, I am posting my OS, OS version, python version, pip version
- [x] I'm posting the complete log, best if using pastebin for long outputs
- [x] I'm using a descriptive title for this issue
## My Issue

On Windows the bot works fine now.

Switching to Debian8 causes:

2016-09-29 18:07:11,966 - **main**:484 - INFO - [15261887] Checking alarm.
2016-09-29 18:07:11,966 - **main**:512 - INFO - [15261887] Checking pokemon and sending notifications.
2016-09-29 18:07:12,108 - **main**:580 - ERROR - [15261887] GeocoderServiceError('HTTP Error 429: Too Many Requests',)
2016-09-29 18:07:42,108 - **main**:484 - INFO - [15261887] Checking alarm.
2016-09-29 18:07:42,108 - **main**:512 - INFO - [15261887] Checking pokemon and sending notifications.
2016-09-29 18:07:42,222 - **main**:580 - ERROR - [15261887] GeocoderServiceError('HTTP Error 429: Too Many Requests',)

Both with the same databse connection over mysql

**Comment by Unknown66** [comment]
You are generating too much Request to the Geocoder Service are you using the api key twice?

**Comment by pki0** [comment]
Do you mean the bot-api-key? No
Each instance of the bot has one api-key.

But people told me maybe the IP of my root-server has an overload with telegram... possible?

**Comment by Unknown66** [comment]
Ah sry we're using openstreetmaps.
Seems like you're generating too much request for them.
Both instances using the same IP?

**Comment by pki0** [comment]
Running maps and 5 bots on Windows (Home IP) works.
Running maps and just 1 and bot on Debain (Root-Server-IP) doesn't work. 
Running maps on Root-IP and 5 bots on Windows works.

I'll try tomorrow on Debian with my home IP

**Comment by Unknown66** [comment]
Mhhh is the rootserver a vserver? 
Then maybe the other instances are using requests too. 
But for sure it's not the telegram api.

**Comment by pki0** [comment]
No it's a dedicated server.

**Comment by Unknown66** [comment]
No idea then.
But tell us tomorrow if you tested.
Hopefully @eugenio412 or @simonward86 do have an idea.

**Comment by pki0** [comment]
Today it's working.
I don't know. Maybe yesterday I had too much requests on my apache or something like this. 

Sorry for opening an issue. Can be closed now
