### ISSUE TITLE
Request: setrarity also sets higher levels

### ISSUE THREAD

**Issue by Korzakov** [eugenio412/PogomBOT#8]
I think it would be nice if the setrarity command would automatically take the higher levels of rarity. So for e.g. you enter command /setrarity 3 it sets notification for category 3, 4 and 5.

Or maybe this should be a new command.

**Comment by eugenio412** [comment]
sorry man, it's easy enough to send two commands in my opinion, did you check the new update?

**Comment by Korzakov** [comment]
Ok, fair enough. Just an idea, because i think when u want category 3 you almost always want notifications for 4 and 5 too. 

No big problem :)
